#!/bin/bash
set -e

# A place to put the original files
mkdir -p ./saved/

# Find transitions and clip the fragments
for video in *.mkv; do
  vedclipmulti "${video}" $(vedbdt "${video}")
  mv "${video}" ./saved/
done

# Remove character selection, transitions, etc
find . -type f -iname "*.mkv" -size -120M -delete

# Pause for manual revision
echo "Press any key after manual revision"
read

# Join everything
vedcat *.mkv

# Print chapters
cat *chapters.lst
