#!/bin/bash
set -e

source vedcommon

file="$1"
extension="$2"

if [[ -z ${file} || -z ${extension} ]]
then
  echo -e "Usage: $0 FILE EXTENSION"
  exit 1
fi

echo -e "Converting \"${file}\" to \"${extension}\""
eval ${VEDUTILS_FFMPEG_CMD} -i "${file}" "${file%.*}.${extension}"
