#!/bin/bash
set -e

workdir="$(pwd)"
vedutils_path="$(dirname $(readlink -f $0))/.."

echo -e "Upgrading vedutils"
cd "$vedutils_path"
git pull origin "$(git rev-parse --abbrev-ref HEAD)"

echo -e "Linking scripts onto PATH"
mkdir -p "$HOME/.local/bin"
ln -sf "$vedutils_path"/vedutils/* "$HOME"/.local/bin/
ln -sf "$vedutils_path"/contrib/* "$HOME"/.local/bin/

cd "$workdir"
echo -e "Done"
