#!/bin/bash
set -e

# Defaults
vedbdt_duration="0.15"
vedbdt_percent="0.95"
segment_duration_minimum="45"

tekken_version="${1:-8}"
case "$tekken_version" in
  "7")
    vedbdt_duration="0.10"
  ;;
  "8")
    vedbdt_duration="0.25"
  ;;
  *)
    vedbdt_duration="0.20"
    tekken_version=""
  ;;
esac

# A place to put the original files
mkdir -p ./original/

# Find transitions and clip the segments, deleting character select and loading screens
for video in *.mkv; do
  segments="$(vedbdt ${video} ${vedbdt_duration} ${vedbdt_percent})"
  fights="$(vedsegtrim lt ${segment_duration_minimum} ${segments})"
  vedclipmulti "${video}" "${fights}"
  mv "${video}" ./original/
done

# Pause for manual revision
echo "Press any key after manual revision"
read

# Join everything
vedcat *clip*.mkv

# Print chapters
chapters="$(cat *chapters.lst | sed 's/Chapter/Fight/')"
echo "$chapters"

# Upload
title="$(ls | grep concatenated\.mkv$ | awk -F '_' '{print $1}' | sed 's/-/ /g')"
youtube-upload \
  --title="tekken${tekken_version} $title" \
  --description="$chapters" \
  --privacy="unlisted" \
  --playlist="Unlisted session dumps" \
  *concatenated.mkv
