#!/bin/bash
set -e

# A place to put the original files
mkdir -p ./saved/

# Find transitions and clip the fragments
for video in *.mkv; do
  vedclipmulti "${video}" $(vedbdt "${video}" 0.10 0.95)
  mv "${video}" ./saved/
done

# Remove character selection, transitions, etc
find . -type f -iname "*.mkv" -size -300M -delete

# Pause for manual revision
echo "Press any key after manual revision"
read

# Join everything
vedcat *.mkv

# Print chapters
chapters="$(cat *chapters.lst | sed 's/Chapter/Fight/')"
echo "$chapters"

# Upload
title="$(ls | grep concatenated\.mkv$ | awk -F '_' '{print $1}' | sed 's/-/ /g')"
youtube-upload \
  --title="tekken7 $title" \
  --description="$chapters" \
  --privacy="unlisted" \
  --playlist="Unlisted session dumps" \
  *concatenated.mkv
