#!/bin/bash

function getFilename() {
  input_file="$1"
  echo "${input_file%.*}"
}

function getFiletype() {
  input_file="$1"
  echo "${input_file##*.}"
}

function getVideoDuration() {
  video_file="$1"
  seconds=$(ffprobe \
    -sexagesimal \
    -v error \
    -show_entries format=duration \
    -of default=noprint_wrappers=1:nokey=1 \
    "$video_file" \
    | awk -F "." '{print $1}')
  echo "$seconds"
}

function timestampToSeconds() {
  timestamp="$1"
  seconds=$(echo $timestamp \
    | awk -F: '{n=0; for(i=NF; i>=1; --i) secs += $i * 60 ^ n++} END {print secs}')
  echo $seconds
}

function secondsToTimestamp() {
  seconds="$1"
  timestamp="$(date -d@$seconds -u +%H:%M:%S)"
  h=$(bc <<< "${1}/3600")
  m=$(bc <<< "(${1}%3600)/60")
  s=$(bc <<< "${1}%60")
  printf "%02d:%02d:%05.2f\n" $h $m $s
}
