#!/bin/bash

set -e

source vedcommon

input_file="$1"
black_duration="${2:-0.05}"
black_ratio="${3:-1.00}"

if [[ -z ${input_file} ]]
then
  echo -e "Usage: $0 VIDEO_FILE [MINIMUM_DURATION_IN_SECONDS] [RATIO_OF_BLACK_IN_FRAME]"
  exit 1
fi

if [[ ! -f "${input_file}" ]]
then
  echo -e "No such file"
  exit 1
fi

timestamps=( \
  $(eval ${VEDUTILS_FFMPEG_CMD} \
    -i "${input_file}" \
    -vf "blackdetect=d=${black_duration}:pic_th=${black_ratio}:pix_th=0.05" \
    -an -f null - 2>&1 \
    | grep blackdetect \
    | sed -u 's/^.* black_start:\(.*\) black_end:\(.*\) .*$/\1 \2/'
  )
)

for i in "${timestamps[@]}"; do
  timestamps_padded=(${timestamps_padded[@]} $(printf "%09.3f" $i))
done

timestamps_grouped=(0 ${timestamps_padded[@]} ${timestamps_padded[@]} 999999999)

IFS=$'\n'
timestamps_sorted=($(sort <<<"${timestamps_grouped[*]}"))
unset IFS

echo ${timestamps_sorted[@]}
