#!/bin/bash

set -e

input_file="$1"
black_duration="${2:-0.05}"
black_ratio="${3:-1.00}"

timestamps=( \
  $(ffmpeg \
    -hwaccel vaapi \
    -i ${input_file} \
    -vf "blackdetect=d=${black_duration}:pic_th=${black_ratio}:pix_th=0.05" \
    -an -f null - 2>&1 \
    | grep blackdetect \
    | sed -u 's/^.* black_start:\(.*\) black_end:\(.*\) .*$/\1 \2/'
  )
)

for i in "${timestamps[@]}"; do
  timestamps_padded=(${timestamps_padded[@]} $(printf "%09.3f" $i))
done

timestamps_grouped=(0 ${timestamps_padded[@]} ${timestamps_padded[@]} 999999999)

IFS=$'\n'
timestamps_sorted=($(sort <<<"${timestamps_grouped[*]}"))
unset IFS

echo ${timestamps_sorted[@]}
