#!/bin/bash

set -e

input_file="$1"

timestamps=( \
  $(ffprobe \
    -f lavfi \
    -i "movie=$input_file, \
      blackdetect=d=0.05:pic_th=1.00:pix_th=0.05" \
    -show_entries tags=lavfi.black_start,lavfi.black_end \
    -print_format default=noprint_wrappers=1:nokey=1 \
    -v quiet \
    | uniq) \
  )

for i in "${timestamps[@]}"; do
  timestamps_padded=(${timestamps_padded[@]} $(printf "%09.3f" $i))
done

timestamps_grouped=(0 ${timestamps_padded[@]} ${timestamps_padded[@]} 999999999)

IFS=$'\n'
timestamps_sorted=($(sort <<<"${timestamps_grouped[*]}"))
unset IFS

echo ${timestamps_sorted[@]}
