#!/bin/bash

set -e

source vedcommon

input_file="$1"
start_time="$(timestampToSeconds $2)"
end_time="$(timestampToSeconds $3)"
duration=$(echo "scale=1; $end_time-$start_time" | bc | sed 's/^\./0./')
output_file="$4"

echo $input_file_name $start_time $end_time $duration

input_file_name="$(getFilename $input_file)"
input_file_type="$(getFiletype $input_file)"

[[ -z $output_file ]] && \
  output_file="${input_file_name}_clip.${input_file_type}"

ffmpeg \
  -hide_banner \
  -hwaccel vaapi \
  -ss $start_time \
  -t $duration \
  -i "$input_file" \
  -pix_fmt yuv420p \
  -c copy \
  -map 0 \
  -avoid_negative_ts make_zero \
  "$output_file"
